name: Cypress Tests
on:
  # schedule:
  #   - cron: "*/3 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
   cypress-intall:
     runs-on: ubuntu-18.04
     container: cypress/browsers:node12.18.3-chrome87-ff82
     steps:
       - name: Checkout
         uses: actions/checkout@v2.4.2
       - name: Cypress run
         uses: cypress-io/github-action@v4.1.1 
         with:
          runTests: false
          build: npm run build
          start: npm start
          parallel: true
          record: true
         env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.SECRETE_GITHUB_TOKEN }} 

    
jobs: 
   cypress-run:
     needs: cypress-intall
     runs-on: ubuntu-18.04
     container: cypress/browsers:node12.18.3-chrome87-ff82
     strategy:
       fail-fast: false
       matrix:
         containers: [1,2,3,4,5,6]
     steps:
       - name: Checkout
         uses: actions/checkout@v2.4.2
       - name: Cypress run
         uses: cypress-io/github-action@v4.1.1 
         with:
          install: false
          build: npm run build
          start: npm start
          parallel: true
          record: true
         env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.SECRETE_GITHUB_TOKEN }} 

              


          
