name: Cypress Tests
on:
  # schedule:
  #   - cron: "*/3 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
   cypress-run:
     runs-on: [self-hosted, X64, Linux]
     steps:
       - name: Checkout
         uses: actions/checkout@v2.4.2
       - name: Setup node
         uses: actions/setup-node@v3
         with:
          node-version: ${{ matrix.node }} 
       

          
