name: Cypress Tests
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
   cypress-run:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v2.4.2
       - name: Cypress.io  
         uses: cypress-io/github-action@v4.1.1 
         with:
          build: npm run build
          start: npm start
         env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    