name: Cypress Tests
on:
  # schedule:
  #   - cron: "*/3 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs: 
   cypress-run:
     runs-on: [self-hosted, X64, Linux]
     steps:
       - name: Checkout
         uses: actions/checkout@v2.4.2
       - run : sudo apt update   
       - run : sudo apt install nodejs npm -y
       - run : sudo apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
       - name: Cypress run
         uses: cypress-io/github-action@v4.1.1 
         with:
          build: npm run build
          start: npm start
          record: true
         env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.SECRETE_GITHUB_TOKEN }} 


          
